# Generated by Django 5.1.4 on 2025-01-01 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(height_field='200px', upload_to='images-Ai/', width_field='100%')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('link', models.URLField()),
            ],
        ),
    ]
