# Generated by Django 5.1.4 on 2025-01-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='icon',
            field=models.ImageField(upload_to='images-Ai/'),
        ),
    ]
