# Generated by Django 5.1.4 on 2025-01-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0002_alter_documentation_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
