# Generated by Django 5.1.4 on 2025-01-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0005_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254)),
                ('feedback_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
