# Generated by Django 5.1.4 on 2025-01-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0007_datafeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home-page/')),
            ],
        ),
    ]
