# Generated by Django 5.1.4 on 2025-01-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0008_homedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='title',
        ),
        migrations.RemoveField(
            model_name='history',
            name='title_type',
        ),
        migrations.AddField(
            model_name='history',
            name='title_link',
            field=models.URLField(null=True),
        ),
    ]
