# Generated by Django 5.1.4 on 2025-01-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI', '0010_alter_history_title_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='title_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
